export const LECTURES = [
	{
		panel: 'ТУЕС',
		title: 'Inside out',
		lecturer: '?',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'ТУЕС',
		title: 'Общността ТУЕС',
		lecturer: 'Мартин Липовски',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'ТУЕС',
		title: 'Животът след ТУЕС',
		lecturer: 'Митко Асенов',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'ТУЕС',
		title: 'ТУЕС извън технологиите - спорт',
		lecturer: 'Калин Златков',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'ТУЕС',
		title: 'ТУЕС извън технологиите - музика',
		lecturer: '?',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Промяната – единствената константа',
		title: 'Бъдещето преди 20 години днес',
		lecturer: 'Иван Житянов',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Промяната – единствената константа',
		title: 'Research in tech',
		lecturer: 'Петър Маймунков',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Промяната – единствената константа',
		title: 'Иновациите, които излизат от Балканите',
		lecturer: 'Яне Френски',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Промяната – единствената константа',
		title: 'Технологиите и науката (това за биологията)',
		lecturer: '?',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Промяната – единствената константа',
		title: 'Данните около нас, как ги организираме и как ги използваме',
		lecturer: '?',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Обичайните заподозрeни',
		title: 'Киберсигурността на държавата ни',
		lecturer: 'Петър Кирков',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'Обичайните заподозрeни',
		title: 'Приемате ли бисквитки? (Дигиталните ни права и GDPR)',
		lecturer: 'Иво Емануилов',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'nz',
		title: 'Креативност и технологии - как технологиите вдъхновяват и подпомагат творческия процес в различни области като рисуване, музика, дизайн етц',
		lecturer: '?',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'nz',
		title: 'What if you accepted the job and realised it’s a mistake 3 weeks in?',
		lecturer: 'Марио Пешев',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'nz',
		title: 'От какво значение са меките уменията когато имаш практическите програмистки знания?',
		lecturer: 'Владислав Янков',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
	{
		panel: 'nz',
		title: 'Какво да вземем по пътя си, за да стигнем, където искаме?',
		lecturer: 'Зарко',
		lecturer_picture: '',
		start: '10:00',
		end: '11:00',
	},
];
